# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game0verflowsapp', '0002_category_url2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url2',
        ),
    ]
